# This file was generated by GoReleaser. DO NOT EDIT.
cask "mctui" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "f7336a026badc8363aa1317ec29104eb8668e31756cb79d5cd7201090777c559"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a2435f53c4eaa6a3a8d832e06cff85dfe6eade6675d4eedd0d12397108552bcd"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e06ac951764dc4d05edaac63e0a06fe252ece998151fea5b423e3c2a68c394d7"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "820c69853d328302f5ca092ab9a2992e37d2a471b21badcaa83711bad7d2f483"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Linux_arm64.tar.gz"
    end
  end

  name "mctui"
  desc "Fast terminal-based Minecraft launcher"
  homepage "https://github.com/aayushdutt/mctui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mctui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mctui"]
    end
  end

  # No zap stanza required

end
