# This file was generated by GoReleaser. DO NOT EDIT.
cask "mctui" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "51b7f85a2da51105ee87e1dcb61d7b9b4c231ac705ab0618d16afa29bf4afa61"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3d2899e07c39cf6250b5b22d34d04b2b86934dd19611a233af79e3b381b7cf3a"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dd6781d07b09d24db51070ff6b3f9b3cccbcc54fcb62a603dd2c96b1f760e4f0"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "04c5012cac95ee68c808696ff5a418111363bf890495ad14e61c3c6c34425152"
      url "https://github.com/aayushdutt/mctui/releases/download/v#{version}/mctui_Linux_arm64.tar.gz"
    end
  end

  name "mctui"
  desc "Fast terminal-based Minecraft launcher"
  homepage "https://github.com/aayushdutt/mctui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mctui"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mctui"]
    end
  end

  # No zap stanza required

end
